{{- range .Values.pullSecrets }}
{{- if and .auth.username .auth.password }}
{{- $username := .auth.username }}
{{- $password := .auth.password }}
{{- $name := default "docker" .name }}
{{- $regId := default "hub.docker.com" .repository }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $files := $.Files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-regcred
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "regcreds.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $files.Get "auth.json" | replace "reg.id" $regId | replace "registry.username" $username | replace "registry.password" $password | replace "registry.auth" $auth | b64enc }}
{{- end }}
{{- end }}
